### ISSUE TITLE
Error when cloning repository

### ISSUE THREAD

**Issue by ericagol** [rodluger/everest-workshop#1]
@rodluger I tried following the instructions to clone the repository, but was met by an error:

EVEREST$ git clone git@github.com:rodluger/everest-workshop.git
Cloning into 'everest-workshop'...
ERROR: We're doing an SSH key audit.
Reason: legacy key automatically unverified
Please visit https://github.com/settings/keys/301569
to approve this key so we know it's safe.
Fingerprint: b3:b4:65:69:23:c1:01:26:0e:b2:38:33:45:37:a8:a9
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I managed to get this to work by forking the repository, and then cloning my fork.

**Comment by rodluger** [comment]
Ok I'll look into it. Thanks!
